export const types = {
  SHOW_MODAL_CALENDAR: '[UI] SHOW_MODAL_CALENDAR',
  SHOW_MODAL_ADD_TASK: '[UI] SHOW_MODAL_ADD_TASK',
  SHOW_MODAL_DETAIL: '[UI] SHOW_MODAL_DETAIL',
  SHOW_MODAL_SUB_TASK: '[UI] SHOW_MODAL_SUB_TASK',
  CHANGE_VIEW: '[UI] CHANGE_VIEW',
  HAS_COLLECTION: '[UI] HAS_COLLECTION',
  SHOW_LOADING: '[UI] SHOW_LOADING',
};
