export const taskTypes = {
  ADD_TASK: '[TASK] ADD_TASK',
  ACTIVE_TASK: '[TASK] ACTIVE_TASK',
  DELETE_TASK: '[TASK] DELETE_TASK',
  EDIT_TASK: '[TASK] EDIT_TASK',
  LOAD_TASKS: '[TASK] LOAD_TASKS',
  SET_DATE: '[TASK] SET_DATE',
  UNSET_DATE: '[TASK] UNSET_DATE',
  ADD_SUB_TASK: '[TASK] ADD_SUB_TASK',
};
